### ISSUE TITLE
handlebars-helpers

### ISSUE THREAD

**Issue by bluerouse** [gi/tilt-handlebars#2]
Hi, great work with this gem! I managed to include my handlebars-partials into an existing project, which did not work with handlebars until now. Really great, thanks!
Now i wondered about one thing: I created some of those handlebars-templates with the npm-handlebar-helpers from assemlbe.io, therefore my question:
Would it be possible to include those helpers on ruby-side, that tilt knows them and renders HTML correctly? Currently i got errors on views, where i used those helpers...

Many thanks for your help!

**Comment by ptrikutam** [comment]
Yes, thank you for putting together this gem! It's very helpful.

I realize it's been quite some time since this issue was opened, but was there any progress made on this front? Also happy to dig into it myself, but was just curious if anyone got further with including external helpers into `tilt-handlebars`.

**Comment by jimothyGator** [comment]
@ptrikutam Sorry, I haven't had much time to give this any TLC. But I will gladly accept pull requests. Unit tests are especially appreciated.

**Comment by gi** [comment]
@bluerouse @ptrikutam
Do either of you have any follow up for this issue?

Both Ruby and JavaScript functions can now be added as helpers. 

See https://github.com/gi/handlebars-ruby.

**Comment by ptrikutam** [comment]
Sorry, I can't remember exactly what I was working on when I posted this issue. I don't think we ended up continuing to use this library.

**Comment by gi** [comment]
Thanks for responding. No worries.
