### ISSUE TITLE
Deprecating therubyracer for mini_racer

### ISSUE THREAD

**Issue by rosatolen** [gi/tilt-handlebars#7]
[therubyracer is no longer actively maintained](https://github.com/rubyjs/therubyracer/issues/462). The old maintainer has recommended using [mini_racer](https://github.com/rubyjs/mini_racer) instead. 

Unfortunately, therubyracer is not compatible with new Apple M1 architecture, whereas mini_racer is.

**Comment by gi** [comment]
This is going to be addressed shortly. 

My company uses this gem as well and has the same issue with the new computers. Hang tight.

**Comment by nonnenmacher** [comment]
see your `https://github.com/gi/handlebars-ruby`, I suppose this will be solution this `tilt` adapter ??

Do you need hand/help test for this ?

We are using it, so we could give some time if need some

**Comment by nonnenmacher** [comment]
sound promising looking at your progress on [handlebars engine](https://github.com/gi/handlebars-ruby) ;-)

only 4 tests won't paste, but I guess this are issues around

https://github.com/rubyjs/mini_racer/issues/225
and 
https://github.com/rubyjs/mini_racer/issues/228

**Comment by gi** [comment]
Thanks. I'll have something posted shortly.
